import json
from datetime import datetime, timedelta

# Get today's date in GMT+7 timezone
now = datetime.utcnow() + timedelta(hours=7)
today_date = now.strftime("%Y-%m-%d")

print(f"Creating a dynamic date solution for {today_date} (GMT+7)")

# Update the main notebook to inject the current date into the Upload_image.ipynb at runtime
with open('SDVN_ComfyUI_Flux_v3.ipynb', 'r', encoding='utf-8') as f:
    notebook = json.load(f)

# Modify the second cell (index 1) to use dynamic date approach
cell = notebook['cells'][1]
source = cell['source']
new_source = [
    '#@title # ⌛️ 2.RUN\n',
    'DriveLib = True\n',
    'RunModels = True #@param {type:"boolean"}\n',
    'CommandLine = "" #@param {type:"string"}\n',
    'install_custom()\n',
    'import time\n',
    'import threading\n',
    'from datetime import datetime, timedelta\n',
    'import os, re\n',
    '\n',
    '# Define a function to run the upload script in a separate thread\n',
    'def run_upload_script():\n',
    '    import time\n',
    '    # Give ComfyUI a moment to start up\n',
    '    time.sleep(10)\n',
    '    print("\\n\\033[1;32mStarting Upload_image.ipynb for model management...\\033[0m")\n',
    '    \n',
    '    # Get today\'s date in GMT+7 timezone\n',
    '    now = datetime.utcnow() + timedelta(hours=7)  # GMT+7\n',
    '    today = now.strftime("%Y-%m-%d")\n',
    '    print(f"\\033[1;32mImages will be saved to folder: {today} (GMT+7 timezone)\\033[0m")\n',
    '    \n',
    '    # Create a dynamic version of Upload_image.ipynb with current date\n',
    '    # First, dynamically create the current date folder\n',
    '    todays_folder = f"/content/drive/MyDrive/SD-Data/Export/ComfyUI/{today}/"\n',
    '    os.makedirs(todays_folder, exist_ok=True)\n',
    '    \n',
    '    # Create a dynamic modified version of Upload_image.ipynb with today\'s date\n',
    '    src_path = "/content/SDVN-WebUI/Upload_image.ipynb"\n',
    '    dst_path = "/tmp/dynamic_upload_image.ipynb"\n',
    '    \n',
    '    # Read the original file\n',
    '    with open(src_path, "r", encoding="utf-8") as f:\n',
    '        content = f.read()\n',
    '    \n',
    '    # Replace the hardcoded date with today\'s date\n',
    '    content = re.sub(\n',
    '        r\'DEFAULT_UPLOAD_FOLDER = \\\'/content/drive/MyDrive/SD-Data/Export/ComfyUI/[^/]*\\\'\',\n',
    '        f\'DEFAULT_UPLOAD_FOLDER = \\\'/content/drive/MyDrive/SD-Data/Export/ComfyUI/{today}/\\\'\',\n',
    '        content\n',
    '    )\n',
    '    content = re.sub(\n',
    '        r\'\\.replace\\(\\\'/content/drive/MyDrive/SD-Data/Export/ComfyUI/[^/]*/\\\'\',\n',
    '        f\'.replace(\\\'/content/drive/MyDrive/SD-Data/Export/ComfyUI/{today}/\\\'\',\n',
    '        content\n',
    '    )\n',
    '    \n',
    '    # Modify the CSS to show thumbnails in a 4-column grid\n',
    '    # 1. Find the beginning of the style section\n',
    '    style_start = content.find("<style>")\n',
    '    style_end = content.find("</style>", style_start)\n',
    '    \n',
    '    if style_start != -1 and style_end != -1:\n',
    '        # Extract the style section\n',
    '        style_section = content[style_start:style_end]\n',
    '        \n',
    '        # Modify the file-list CSS for grid layout instead of scroll\n',
    '        new_style_section = style_section.replace(\n',
    '            ".file-list {\\n            background-color: #f7f7f7;\\n            padding: 15px;\\n            border-radius: 5px;\\n            margin-top: 20px;\\n            max-height: 400px;\\n            overflow-y: auto;\\n        }",\n',
    '            ".file-list {\\n            background-color: #f7f7f7;\\n            padding: 15px;\\n            border-radius: 5px;\\n            margin-top: 20px;\\n            display: grid;\\n            grid-template-columns: repeat(4, 1fr);\\n            grid-gap: 15px;\\n        }"\n',
    '        )\n',
    '        \n',
    '        # Update file-item to display as cards in the grid\n',
    '        new_style_section = new_style_section.replace(\n',
    '            ".file-item {\\n            display: flex;\\n            justify-content: space-between;\\n            align-items: center;\\n            padding: 8px 0;\\n            border-bottom: 1px solid #eee;\\n        }",\n',
    '            ".file-item {\\n            display: flex;\\n            flex-direction: column;\\n            background-color: white;\\n            border-radius: 8px;\\n            box-shadow: 0 2px 4px rgba(0,0,0,0.1);\\n            padding: 10px;\\n            transition: transform 0.2s;\\n        }\\n        .file-item:hover {\\n            transform: translateY(-5px);\\n            box-shadow: 0 5px 15px rgba(0,0,0,0.1);\\n        }"\n',
    '        )\n',
    '        \n',
    '        # Update thumbnail size\n',
    '        new_style_section = new_style_section.replace(\n',
    '            ".file-thumbnail {\\n            width: 450px;\\n            height: 450px;\\n            object-fit: cover;\\n            margin-right: 30px;\\n            border-radius: 10px;\\n        }",\n',
    '            ".file-thumbnail {\\n            width: 100%;\\n            height: 180px;\\n            object-fit: cover;\\n            border-radius: 6px;\\n            margin-bottom: 10px;\\n        }"\n',
    '        )\n',
    '        \n',
    '        # Update file info display\n',
    '        new_style_section = new_style_section.replace(\n',
    '            ".file-info {\\n            flex-grow: 1;\\n            margin-right: 15px;\\n            word-break: break-all;\\n        }",\n',
    '            ".file-info {\\n            font-size: 12px;\\n            margin-bottom: 10px;\\n            word-break: break-all;\\n            max-height: 50px;\\n            overflow: hidden;\\n            text-overflow: ellipsis;\\n        }"\n',
    '        )\n',
    '        \n',
    '        # Update file actions for buttons\n',
    '        new_style_section = new_style_section.replace(\n',
    '            ".file-actions {\\n            display: flex;\\n            justify-content: space-between;\\n            gap: 10px;\\n            margin-top: 5px;\\n        }",\n',
    '            ".file-actions {\\n            display: flex;\\n            justify-content: space-between;\\n            gap: 5px;\\n            margin-top: auto;\\n        }"\n',
    '        )\n',
    '        \n',
    '        # Make buttons smaller\n',
    '        new_style_section = new_style_section.replace(\n',
    '            "button, .btn {\\n            background-color: #4285f4;\\n            color: white;\\n            border: none;\\n            padding: 8px 16px;\\n            border-radius: 4px;\\n            cursor: pointer;\\n            font-size: 14px;\\n            text-decoration: none;\\n            display: inline-block;\\n        }",\n',
    '            "button, .btn {\\n            background-color: #4285f4;\\n            color: white;\\n            border: none;\\n            padding: 5px 10px;\\n            border-radius: 4px;\\n            cursor: pointer;\\n            font-size: 12px;\\n            text-decoration: none;\\n            display: inline-block;\\n            flex: 1;\\n            text-align: center;\\n        }"\n',
    '        )\n',
    '        \n',
    '        # Replace the style section in the content\n',
    '        content = content[:style_start] + "<style>\\n" + new_style_section[len("<style>\\n"):] + content[style_end:]\n',
    '    \n',
    '    # Write the modified file\n',
    '    with open(dst_path, "w", encoding="utf-8") as f:\n',
    '        f.write(content)\n',
    '    \n',
    '    print(f"Created dynamic version of Upload_image.ipynb with current date: {today} and 4-column thumbnail grid")\n',
    '    \n',
    '    # Run the modified version\n',
    '    %run /tmp/dynamic_upload_image.ipynb\n',
    '\n',
    '# Start the upload script in a separate thread if enabled\n',
    'if RunModels:\n',
    '    thread = threading.Thread(target=run_upload_script)\n',
    '    thread.daemon = True\n',
    '    thread.start()\n',
    '    print("\\033[1;33mModel uploader will start shortly in the background...\\033[0m")\n',
    '\n',
    '# Run ComfyUI\n',
    'run_ver(Version, CommandLine)\n'
]
notebook['cells'][1]['source'] = new_source

# Write the modified notebook
with open('SDVN_ComfyUI_Flux_v3.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, ensure_ascii=False, indent=1)

print('SDVN_ComfyUI_Flux_v3.ipynb updated with dynamic date functionality and 4-column thumbnail grid!') 